version: "3"
volumes:
    db:
services:
  app:
    container_name: app
    restart: unless-stopped
    tty: true
    build:
      context: docker/php/.
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    env_file:
      - .env
    environment:
      DOCUMENTROOT: ${DOCUMENTROOT}
    volumes:
      - "./:/var/www/html"
    ports:
      - ${PORTA_HTTP}:80
      - ${PORTA_HTTPS}:443
    depends_on:
      - db
  db:
    container_name: db
    restart: unless-stopped
    tty: true
    build:
      context: docker/postgres/.
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    env_file:
      - .env
    volumes:
        - db:/var/lib/postgresql/data
    ports:
      - ${PORTA_POSTGRESQL}:5432
  redis:
    container_name: redis
    restart: unless-stopped
    tty: true
    build:
      context: docker/redis
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    env_file:
      - .env
    ports:
      - ${PORTA_REDIS}:6379
